[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = "0.8.21"
serde = "1.0.210"
serde_json = "1.0.128"
uuid = { version = "1", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }