[package]
name = "controllers"
version = "0.1.0"
edition = "2021"

[dependencies]
clients = { path = "../clients" }
shared = { path = "../shared" }
models = { path = "../models" }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "any", "postgres"] }
